# Core multi-task and regression runs (biochemical + cellular).
global:
  models_dir: /path/to/models
  temp_dir: /path/to/temp
  cpus: 4
  seed: 1337
  submit: false
  datasets:
    bio_reg: /path/to/processed/all/biochemical_regression.parquet
    bio_mt: /path/to/processed/all/biochemical_multilabel.parquet
    cell_reg: /path/to/processed/all/cellular_regression.parquet
    cell_mt: /path/to/processed/all/cellular_multilabel.parquet

tasks:
  # Multi-task
  - type: multilabel
    job_name: mt_bio
    trainval_path: bio_mt
    predict_test: true
    split_seed: 1337

  - type: multilabel
    job_name: mt_cell
    trainval_path: cell_mt
    predict_test: true
    split_seed: 1337

  # Regression
  - type: regression
    job_name: reg_bio_min20
    trainval_path: bio_reg
    target_column: target
    compound_min_screens: 20
    compound_screens_column: screens
    screens_weight_mode: linear
    predict_test: true
    split_seed: 1337

  - type: regression
    job_name: reg_bio_min50
    trainval_path: bio_reg
    target_column: target
    compound_min_screens: 50
    compound_screens_column: screens
    screens_weight_mode: linear
    predict_test: true
    split_seed: 1337

  - type: regression
    job_name: reg_cell_min20
    trainval_path: cell_reg
    target_column: target
    compound_min_screens: 20
    compound_screens_column: screens
    screens_weight_mode: linear
    predict_test: true
    split_seed: 1337
